# Support Vector Machine (SVM):

In [1]:
import os 
print(os.listdir())

['Support-Vector-Machine.ipynb', '.ipynb_checkpoints', 'Social_Network_Ads.csv']


In [2]:
# Importing Libraries :
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [3]:
# loading dataset :
data = pd.read_csv('Social_Network_Ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
## Split dataset into X (Independent Variables) and y (dependent varibles) matrices :
X = data.iloc[:, [2,3]].values
y = data.iloc[:, 4].values

In [6]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [7]:
# Spliting X and y into Training and testing data :
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
y_test

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [10]:
# Feature scaling :
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_test

array([[-0.48002572, -1.21513327],
       [ 0.09030187, -0.31809663],
       [-0.09980733, -0.23128664],
       [ 0.85073866, -0.60746329],
       [-0.28991653,  0.05808002],
       [ 0.85073866, -0.54958996],
       [-0.09980733, -0.37596996],
       [-1.71573551,  0.46319334],
       [-0.95529872,  0.26063668],
       [-0.76518952,  0.55000334],
       [-1.43057171, -0.20234997],
       [-1.24046251,  0.49213001],
       [ 0.28041107, -0.52065329],
       [ 0.09030187,  0.08701669],
       [-0.19486193, -0.57852662],
       [-0.28991653, -0.66533662],
       [ 1.70623005, -0.28915997],
       [-0.76518952,  1.33129332],
       [-1.33551711, -0.3470333 ],
       [-0.76518952, -0.23128664],
       [ 0.75568406,  0.11595335],
       [ 1.89633924,  0.72362333],
       [ 1.42106625, -1.04151328],
       [ 1.89633924, -0.92576661],
       [-0.19486193, -1.07044994],
       [-0.48002572, -0.28915997],
       [-0.28991653, -1.30194327],
       [-1.24046251,  0.26063668],
       [-1.33551711,

## Implementing SVM:

In [14]:
# Importing library:
from sklearn.svm import SVC

In [15]:
classifier = SVC(kernel='linear')

In [16]:
classifier.fit(X_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
# precting :
y_predictor = classifier.predict(X_test)
y_predictor

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [18]:
# Confusion Matrix to check false pasitives :
from sklearn.metrics import confusion_matrix

In [19]:
errors = confusion_matrix(y_test, y_predictor)
errors

array([[79,  3],
       [10, 28]])